### ISSUE TITLE
Pre-processing to generate 512x512 patches of FFHQ dataset

### ISSUE THREAD

**Issue by Mayongrui** [chaofengc/FeMaSR#14]
Hi there, sorry for bothering again.

After reading the supplementary materials, I tried to reproduce the pre-processing code for data preparation. The code is as follows:

![image](https://user-images.githubusercontent.com/31749987/190097202-97ca0997-47ce-4e4f-9cae-0977a67e018a.png)

This code should work for patch slicing and selection (ensure the gradient fits the scene). However, the total (patches satisfy the requirements) number is only a few hundred, much less than the number reported in the supplementary documents. 

Would you mind providing me with more details or the pre-processing code for patch slicing and selection?

**Comment by chaofengc** [comment]
First of all, we use `var < 10` not `std < 10`, `sqrt` is not needed in line 23.
Secondly, we later found that such preprocessing is actually not necessary, and you may simply crop patches without any preprocessing.

**Comment by Mayongrui** [comment]
Got it. Thanks for your help, I may skip the selection part for dataset preparation.
