### ISSUE TITLE
results of vqgan

### ISSUE THREAD

**Issue by Winnie202** [chaofengc/FeMaSR#16]
Thank you for sharing the code,I did the first part of the image reconstruction for Street View,but text sections don't work well. how should I optimize the reconstruction results of vqgan with  text,like these:

![00002](https://user-images.githubusercontent.com/86768013/233959968-ff8d742e-2e94-4153-b588-e5055606da41.jpg)

![00002](https://user-images.githubusercontent.com/86768013/233960118-06477645-50be-4a3f-b547-88448995ce64.jpg)

**Comment by chaofengc** [comment]
The reconstruction of tiny textures like small text remains an inherent challenge with VQGAN and presents a significant difficulty to resolve. You may refer to the following work if interested in this problem:

https://github.com/joanrod/ocr-vqgan

**Comment by Winnie202** [comment]
> The reconstruction of tiny textures like small text remains an inherent challenge with VQGAN and presents a significant difficulty to resolve. You may refer to the following work if interested in this problem:
> 
> https://github.com/joanrod/ocr-vqgan

thanks
