### ISSUE TITLE
Bug encountered when specifying 'weight' argument during inference.

### ISSUE THREAD

**Issue by Luo-Yihang** [chaofengc/FeMaSR#18]
It seems like need to change `weight_path = args.w` in line 36 of the `inference_femasr.py` file to `weight_path = args.weight`. Otherwise, might encounter the following error when a user specifies the `weight` argument during inference:

```
File "./FeMaSR/inference_femasr.py", line 36, in main
    weight_path = args.w
AttributeError: 'Namespace' object has no attribute 'w'
```

**Comment by chaofengc** [comment]
That's correct. Thanks for your information !
