### ISSUE TITLE
About multi-code texture visualization

### ISSUE THREAD

**Issue by Wolfybox** [chaofengc/FeMaSR#5]
I am trying to reproduce the code visualization part of your paper, and successfully generate reconstructed texture under the single code 
 cases., which I referred to this code snippet:

![image](https://user-images.githubusercontent.com/32531785/167557638-45cba07b-11a7-4de3-a466-efd0d702822b.png)

I am wondering whether there is any implementation for visualzation of multi-codes visualization:

![image](https://user-images.githubusercontent.com/32531785/167557208-27fe028c-e816-42a2-ae2b-4708e7dbd637.png)

**Comment by chaofengc** [comment]
Here are the steps to visualize multiple codes:

1. Remove unused codes. VQGAN cannot make full use of all the codes in the codebook, and many of them are never used. By forwarding certain number of images through the pretrained vqgan, you should able to figure out the indexes of useful codes;
2. After getting the useful subsets, random select `2, 3, 4, 8` codes, and use these sub-subsets to obtain the latent feature maps which are the input of decoder. Order of codes are not matter here.

Different subsets correspond to different semantic textures. We did not investigate such correspondence in detail, and only provide naïve visualizations in the paper.

**Comment by Wolfybox** [comment]
> Here are the steps to visualize multiple codes:
> 
> 1. Remove unused codes. VQGAN cannot make full use of all the codes in the codebook, and many of them are never used. By forwarding certain number of images through the pretrained vqgan, you should be able to figure out the indexes of useful codes;
> 2. After getting the useful subsets, random select `2, 3, 4, 8` codes, and use these sub-subsets to obtain the latent feature maps which are the input of decoder. Order of codes is not matter here.
> 
> Different subsets correspond to different semantic textures. We did not investigate such correspondence in detail, and only provide naïve visualizations in the paper.

Thanks for the detailed explanation. 
About the first point (unused), I had similar observations by visualizing the code indices matrix during my experiments -- Only certain sets of codes are frequently used during forward. Addtionally, for those duplicate or redudant patterns like backgrounds or monotonous texture, the model  tends to use only one or two codes for representation. 
I'll try those steps you mention and come back with my reproduction. : )

**Comment by chaofengc** [comment]
Example visualization code is provided in https://github.com/chaofengc/FeMaSR/blob/main/vis_codebook.py
