### ISSUE TITLE
swin-transformer

### ISSUE THREAD

**Issue by Nirvana-feng** [chaofengc/FeMaSR#8]
Hello, can you provide the code in the paper discovqa: temporary destruction content transformers for video quality assessment or extract features with swin transformer. Thank you very much

**Comment by Nirvana-feng** [comment]
Hello, what month will the paper be released

**Comment by chaofengc** [comment]
Not sure. The paper is still under submission.

**Comment by Nirvana-feng** [comment]
OK, thank you
