### ISSUE TITLE
About Training Details

### ISSUE THREAD

**Issue by huicongzhang** [chaofengc/FeMaSR#9]
"The model pretraining stage takes about 3 days on 2 GeForce RTX 3090 GPUs" in paper. However I use the same settings and it takes 10 days to train on the V100 GPUs.  I want to confirm the total training iter is 2000000 in model pretraining stage?

**Comment by chaofengc** [comment]
The proper iteration num is 200k as described in the paper. Training for longer time with larger batch size may get better performance.
